pipeline:
    build:
        image: itapteka/fake
        pull: true
        volumes:
            - /home/dsemenov87/nuget/:/root/.nuget/packages
        environment:
            - PG_HOST=localhost
            - REDIS_HOST=0.0.0.0
            - TAX_CALCULATOR_DB_NAME=taxcalculator
        commands:
            - dotnet /usr/local/bin/fake/fake.dll -v run build.fsx

    publish-feature:
        image: plugins/docker
        repo: itapteka/taxcalculator
        auto_tag: true
        auto_tag_suffix: ${DRONE_BRANCH}
        username: itapteka
        password: itapteka
        # volumes:
        #     - /var/run/docker.sock:/var/run/docker.sock
        # when:
        #     branch: feature/*

    deploy-feature-kube:
        image: vallard/drone-kube
        template: ./k8s/deployment.yaml
        namespace: $DRONE_BRANCH
        server: https://95.163.251.232:6443
        when:
            branch: feature/*

services:
  db:
    image: postgres:alpine

  cache:
    image: redis:alpine
