pipeline:
    restore-cache:
        image: drillster/drone-volume-cache
        restore: true
        mount:
            - /drone/nuget_packages
        volumes:
            - /var/lib/drone/cache:/cache

    build:
        image: itapteka/fake
        pull: true
        environment:
            - NUGET_PACKAGES=/drone/nuget_packages
        commands:
            - /usr/local/bin/fake/fake run ./build.fsx

    rebuild-cache:
        image: drillster/drone-volume-cache
        rebuild: true
        mount:
            - /drone/nuget_packages
        volumes:
            - /var/lib/drone/cache:/cache

    # integrational-tests:
    #     image: itapteka/fake
    #     environment:
    #         - NUGET_PACKAGES=/drone/nuget_packages
    #         - PG_HOST="db"
    #         - REDIS_HOST="cache"
    #         - TAX_CALCULATOR_DB_NAME="taxcalculator"
    #     commands:
    #         - ./build.fsx IntegrationalTests

    # publish-feature:
    #     image: plugins/docker
    #     repo: dsemenov871.fvds.ru/task-service
    #     tags: [ $DRONE_BRANCH ]
    #     # volumes:
    #     #     - /var/run/docker.sock:/var/run/docker.sock
    #     when:
    #         branch: feature/*

    # deploy-feature:
    #     image: rics3n/drone-ansible:2
    #     playbook: deploy/feature.yml
    #     volumes:
    #         - /etc/ansible/staging:/etc/ansible
    #     when:
    #         branch: feature/*

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:alpine