pipeline:
    build:
        image: itapteka/fake
        pull: true
        volumes:
            - /home/dsemenov87/nuget/:/root/.nuget/packages
        commands:
            - dotnet test ./test/TaxCalculator/TaxCalculator.BusinessLogic.UnitTests/BusinessLogic.UnitTests.csproj

    integrational-tests:
        image: itapteka/fake
        pull: true
        volumes:
            - /home/dsemenov87/nuget/:/root/.nuget/packagest
        environment:
            - NUGET_PACKAGES=/drone/nuget_packages
            - PG_HOST="db"
            - REDIS_HOST="cache"
            - TAX_CALCULATOR_DB_NAME="taxcalculator"
        commands:
            - dotnet /usr/local/bin/fake/fake.dll -v run build.fsx -t IntegrationalTests

    # publish-feature:
    #     image: plugins/docker
    #     repo: dsemenov871.fvds.ru/task-service
    #     tags: [ $DRONE_BRANCH ]
    #     # volumes:
    #     #     - /var/run/docker.sock:/var/run/docker.sock
    #     when:
    #         branch: feature/*

    # deploy-feature:
    #     image: rics3n/drone-ansible:2
    #     playbook: deploy/feature.yml
    #     volumes:
    #         - /etc/ansible/staging:/etc/ansible
    #     when:
    #         branch: feature/*

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:alpine